"""fix habitlog foreign key

Revision ID: 004cabebbf98
Revises: 6a7b2207dab9
Create Date: 2025-12-18 00:52:15.989046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004cabebbf98'
down_revision: Union[str, Sequence[str], None] = '6a7b2207dab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("habitlog") as batch_op:
        batch_op.create_foreign_key(
            "fk_habitlog_habit_id_habit",
            "habit",
            ["habit_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habitlog', type_='foreignkey')
    # ### end Alembic commands ###
