"""add user model and link habits

Revision ID: bd4bbff2e124
Revises: 004cabebbf98
Create Date: 2026-01-26 18:56:02.200846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4bbff2e124'
down_revision: Union[str, Sequence[str], None] = '004cabebbf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'])
    op.add_column('habitlog', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habitlog', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habitlog', type_='foreignkey')
    op.drop_column('habitlog', 'user_id')
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.drop_column('habit', 'user_id')
    # ### end Alembic commands ###
